name: creator-hardcore
version: '${version}'
main: be.sv3r.creatorhardcore.CreatorHardcore
description: CreatorSMP Hardcore
author: Sv3r
api-version: '1.21'
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true